=head1 NAME

Promises - who has promised an article

=head1 DESCRIPTION

This lists who has promised an article for 2014 advent calendar.

In a summary:

=over

=item There are nine promises for articles outstanding

=item Mark has written and committed seven articles so far

=item Mark has three articles "in progress" nearing completion

=item There is one "possible" article

=back

  perl -E 'say 24 - (9 + 7 + 3 + 1)'
  4

=head2 Promises

=over

=item Marcus Ranberg

Marcus promised us an article on something Mojo related.

=item Dave Cross

Dave promised an article around the 1st.

=item Olaf Anders

Promised an article on MetaCPAN around Nov 30th

=item Paul Evans

Is going to write an article on List::UtilsBy

=item John SJ Anderson

Promised an article.  Said he'd think about topics over thanksgiving

=item Neil Bowers

Promised an article towords the end of the month

=item Augustina Ragwitz

Was writing an article on AnyEvent

=item Graham Ollis

Was writing an article on FFI::Raw

=item Ricardo Signes

Has promised an article.

=back

=head2 Maybes

=over

=item Jeffrey Ryan Thalhammer

Said he'd think about it over thanksgiving and get back to me

=back

