=head1 NAME

Promises - who has promised an article

=head1 DESCRIPTION

This lists who has promised an article for 2014 advent calendar.

In a summary:

=over

=item There are five promises for articles outstanding

=item There are four articles delivered and in the queue

=item Mark has written and committed eight articles so far

=back

  perl -E 'say 24 - (5 + 8 + 4)'
  7

Wow, that's a lot of articles for me to write.

=over

=item There is one half written articls

=item There are three articls Mark is fairly confident he can write

=back

  perl -E 'say 24 - (5 + 8 + 4 + 1 + 3)'
  3

Current prediction: We need B<three> more articles if Mark isn't going to
go insane.

=head2 Delivered

You all rock!

=over

=item Graham Ollis

Was writing an article on FFI::Raw

=item Marcus Ranberg

Marcus promised us an article on something Mojo related.

=item Dave Cross

Dave promised an article around the 1st.

=item Neil Bowers

Originally promised an article towords the end of the month.  Now saying
around the 8th.  Go Neil!

=back

=head2 Promises

=over

=item Olaf Anders

Promised an article on MetaCPAN around Nov 30th.  Now working with Neil
to deliver articls around the 8th.

=item Paul Evans

Is going to write an article on List::UtilsBy

=item John SJ Anderson

Promised an article.  Said he'd think about topics over thanksgiving

=item Augustina Ragwitz

Was writing an article on AnyEvent

=item Ricardo Signes

Has promised an article.

=back

=head2 Mark's Outstanding Articles

Mostly written

=over

=item App::ack

Yes, I'm aware that this was featured before.  But that was eight years
ago now.

=back

Planned articles

=over

=item MooX::Options

=item Reply (and Ply)

=item Date::ICal::DateTime

Fun article about planning christmas day.  Date manipulation when to
put the turkey in the oven.  Timezone support so I can watch the
Queen's speech.

=back

Possible ideas if no-one comes up with anything better

=over

=item App::cpanminus

Easy installation from the commmand line from the cpan.  Installing
from a checkout.  Installing direct from github.

=item Capture::Tiny

=back


