#!perl
use 5.19.9;
use warnings;

use feature qw(postderef postderef_qq);
no warnings 'experimental::postderef';

use utf8;
use open qw(:std :encoding(UTF-8));

use YAML::XS qw( LoadFile );

use FindBin;
use lib "$FindBin::Bin/lib";
use PerlAdvent::Authors qw( normalize_key );

my $out = $ARGV[0];
die "usage: mkarchives OUTDIR\n" unless length $out and -d $out;

my $MAIN_TEMPLATE = <<'END';
<html><head><title>Perl Advent Calendar Archives</title></head>
<body>
<h1>Perl Advent Calendar Archives</h1>

<h2>Previous Calendars</h2>
<ul>
%LIST%
</ul>

<h3><a href="archives-AZ.html">Alphabetical Module Listing</a></h3>
<h3><a href="archives-Yd.html">Chronological Module Listing</a></h3>
<h3><a href="archives-author.html">Listing by Author</a></h3>
</body></html>
END

my ($archives) = LoadFile('archives.yaml');

{
  my $lis = join qq{\n},
            map {; "<li><a href='$_'>$_</a></li>" }
            sort keys %$archives;

  my $main = $MAIN_TEMPLATE =~ s/%LIST%/$lis/r;

  open my $main_out, '>', "$out/archives.html" or die "error opening: $!";
  print $main_out $main;
  close $main_out or die "error closing archive.html: $!"
}

my $AZ_TEMPLATE = <<'END';
<html><head><title>Perl Advent Calendar Archives</title></head>
<body>
<h1>Perl Advent Calendar Archives</h1>

<ul>
%LIST%
</ul>

<h3><a href="archives.html">Listing of All Years</a></h3>
<h3><a href="archives-Yd.html">Chronological Topic Listing</a></h3>
<h3><a href="archives-author.html">Listing by Author</a></h3>
</body></html>
END

my $DATE_TEMPLATE = <<'END';
<html><head><title>Perl Advent Calendar Archives</title></head>
<body>
<h1>Perl Advent Calendar Archives</h1>

<ul>
%LIST%
</ul>

<h3><a href="archives.html">Listing of All Years</a></h3>
<h3><a href="archives-AZ.html">Alphabetical Topic Listing</a></h3>
<h3><a href="archives-author.html">Listing by Author</a></h3>
</body></html>
END

my $AUTHOR_TEMPLATE = <<'END';
<html><head><meta charset="utf-8"><title>Perl Advent Calendar Archives</title></head>
<body>
<h1>Perl Advent Calendar Archives</h1>

<h2>Articles by Author</h2>
%LIST%

<h3><a href="archives.html">Listing of All Years</a></h3>
<h3><a href="archives-AZ.html">Alphabetical Topic Listing</a></h3>
<h3><a href="archives-Yd.html">Chronological Topic Listing</a></h3>
</body></html>
END

{
  my %by_name;
  my %by_date;
  my %by_author;
  my @unattributed;

  for my $year (sort keys $archives->%*) {
    for my $day (sort keys $archives->{ $year }->%*) {
      my $link = ($year >= 2011)
               ? sprintf("%d/%d-12-%02d.html", $year, $year, $day)
               : sprintf("%d/%02d", $year, $day);

      ENTRY: for my $entry ($archives->{$year}{$day}->@*) {
        my $date = sprintf('%d-12-%02d', $year, $day);

        my $item = {
          article_link => $link,
          date => $date,
        };

        if ($entry->{module}) {
          $item->{title} = $entry->{module};
          $item->{href}  = "https://metacpan.org/module/$entry->{module}";
        } elsif ($entry->{topic}) {
          $item->{title} = $entry->{topic};
          $item->{href}  = $entry->{href} if $entry->{href};
        } else {
          # ???
          next ENTRY;
        }

        push $by_name{ $item->{title} }->@*, $item;
        push $by_date{ $item->{date} }->@*, $item;

        # Group by author. Entries with a missing/empty/whitespace-only
        # author are collected into an "Author unknown" worklist rather than
        # silently omitted, so their true authors can be tracked down later.
        my $author = $entry->{author};
        if ( defined $author and $author =~ /\S/ ) {
          my $key = normalize_key($author);
          $by_author{$key}{display} //= $author;
          push $by_author{$key}{items}->@*, $item;
        }
        else {
          push @unattributed, $item;
        }
      }
    }
  }

  my ($az_lis, $date_lis) = (q{}) x 2;

  for my $name (sort { fc $a cmp fc $b } keys %by_name) {
    for my $item ($by_name{$name}->@*) {
      # XXX: need to entity encode -- rjbs, 2014-03-11
      $az_lis .= "<li><a href='$item->{article_link}'>$item->{date}</a>"
              .  " &mdash; "
              .  ($item->{href}
                 ? "<a href='$item->{href}'>$item->{title}</a>"
                 : $item->{title})
              . "\n";
    }
  }

  for my $date (sort keys %by_date) {
    # XXX crude duplication of code above -- rjbs, 2014-03-11
    for my $item ($by_date{$date}->@*) {
      # XXX: need to entity encode -- rjbs, 2014-03-11
      $date_lis .= "<li><a href='$item->{article_link}'>$item->{date}</a>"
                .  " &mdash; "
                .  ($item->{href}
                   ? "<a href='$item->{href}'>$item->{title}</a>"
                   : $item->{title})
                . "\n";
    }
  }

  my $az = $AZ_TEMPLATE =~ s/%LIST%/$az_lis/r;
  open my $az_out, '>', "$out/archives-AZ.html" or die "error opening: $!";
  print $az_out $az;
  close $az_out or die "error closing archive-AZ.html: $!";

  my $date = $DATE_TEMPLATE =~ s/%LIST%/$date_lis/r;
  open my $date_out, '>', "$out/archives-Yd.html" or die "error opening: $!";
  print $date_out $date;
  close $date_out or die "error closing archive-Yd.html: $!";

  my $author_lis = q{};
  for my $key (sort { fc $a cmp fc $b } keys %by_author) {
    my $display = $by_author{$key}{display};
    $author_lis .= "<h3>" . enc($display) . "</h3>\n<ul>\n";
    my @items = sort { $a->{date} cmp $b->{date} }
                $by_author{$key}{items}->@*;
    for my $item (@items) {
      $author_lis .= "<li><a href='$item->{article_link}'>$item->{date}</a>"
                  .  " &mdash; "
                  .  ($item->{href}
                     ? "<a href='$item->{href}'>" . enc($item->{title}) . "</a>"
                     : enc($item->{title}))
                  . "\n";
    }
    $author_lis .= "</ul>\n";
  }

  # A visible worklist of still-unattributed articles (2005, scattered
  # missing legacy days, most of 2021). See issue #688.
  if (@unattributed) {
    $author_lis .= "<h2>Author unknown</h2>\n";
    $author_lis .= "<p>Help us attribute these &mdash; see "
                .  "<a href='https://github.com/perladvent/Perl-Advent/issues/688'>issue #688</a>.</p>\n"
                .  "<ul>\n";
    for my $item (sort { $a->{date} cmp $b->{date} } @unattributed) {
      $author_lis .= "<li><a href='$item->{article_link}'>$item->{date}</a>"
                  .  " &mdash; "
                  .  ($item->{href}
                     ? "<a href='$item->{href}'>" . enc($item->{title}) . "</a>"
                     : enc($item->{title}))
                  . "\n";
    }
    $author_lis .= "</ul>\n";
  }

  my $author = $AUTHOR_TEMPLATE =~ s/%LIST%/$author_lis/r;
  open my $author_out, '>', "$out/archives-author.html" or die "error opening: $!";
  print $author_out $author;
  close $author_out or die "error closing archives-author.html: $!";
}

sub enc {
  my ($s) = @_;
  return '' unless defined $s;
  $s =~ s/&/&amp;/g;
  $s =~ s/</&lt;/g;
  $s =~ s/>/&gt;/g;
  return $s;
}
