#!/usr/bin/env perl
#===============================================================================
#
#         FILE: year2yaml
#
#        USAGE: year2yaml YYYY [ outfile ]
#
#  DESCRIPTION: Append the given year's topics to the archives.yaml file
#
#      OPTIONS: If the outfile is specified, use that instead of
#               'archives.yaml'
# REQUIREMENTS: ---
#         BUGS: Assumes every topic is a module
#        NOTES: ---
#       AUTHOR: Pete Houston (pete), cpan@openstrike.co.uk
# ORGANIZATION: Openstrike
#      VERSION: 1.0
#      CREATED: 05/07/23
#===============================================================================

use strict;
use warnings;
use 5.010;
use open qw(:std :encoding(UTF-8));

use FindBin;
use lib "$FindBin::Bin/lib";
use PerlAdvent::Authors qw( parse_author_from_header canonical_author load_aliases yaml_escape_dq );
use YAML::XS ();

my $aliases = load_aliases("$FindBin::Bin/authors-aliases.yaml");

my ($year, $archfile) = @ARGV;
die "You must provide the year as the first argument.\n"
	unless defined $year;
$year =~ /^\d{4}$/ or die "Bad year: $year\n";
my $ydir = "$year/articles";
$archfile //= 'archives.yaml';

die "No articles found for $year\n" unless -d $ydir;

my $ytext = "\n$year:\n";
my $yh;
for my $day (1 .. 25) {
	my $file = sprintf "$ydir/%4.4i-12-%2.2i.pod", $year, $day;
	print "Processing file $file\n";
	my @modlist;
	my $header = q{};
	next unless -e $file;
	open my $ifh, '<', $file or die "Cannot open $file for reading: $!";
	while (my $line = <$ifh>) {
		$header .= $line if $line =~ /\S/;
		if ($line =~ /^Topic: (.+?)\s*$/) {
			my @topics = split /\s*,\s*/, $1;
			for my $topic (@topics) {
				$topic =~ s/^\s+|\s+$//g;
				# If topic contains spaces but all space-separated parts look like
				# module names (contain ::), split them into individual entries
				if ($topic =~ / /) {
					my @parts = split /\s+/, $topic;
					if (!grep { !/::/ } @parts) {
						print "Found module $_\n" for @parts;
						push @modlist, map { { module => $_ } } @parts;
						next;
					}
				}
				my $key = ($topic =~ /::/) ? 'module' : 'topic';
				print "Found $key $topic\n";
				push @modlist, { $key => $topic };
			}
		}
		last unless $line =~ /\S/;
	}
	close $ifh;
	next unless @modlist;

	my $raw_author = parse_author_from_header($header);
	my $author = defined $raw_author
		? canonical_author($raw_author, $aliases)
		: undef;

	$ytext .= sprintf "  %2.2i:\n", $day;
	for my $entry (@modlist) {
		my ($key, $val) = %$entry;
		my $safe_val = yaml_escape_dq($val);
		if (defined $author and length $author) {
			my $safe = yaml_escape_dq($author);
			$ytext .= qq#  - { "$key" : "$safe_val", author: "$safe" }\n#;
		} else {
			$ytext .= qq#  - { "$key" : "$safe_val" }\n#;
		}
	}
}

# Safety net: validate the appended block parses as YAML before it can reach
# the committed archives.yaml. Wrap the "  DD:" / "  - { ... }" lines in a
# minimal parseable top-level key so YAML::XS::Load sees a complete document.
{
	my $wrapper = "_validate:\n$ytext";
	my $ok = eval { YAML::XS::Load($wrapper); 1 };
	die "Refusing to append: generated YAML for $year does not parse: $@"
		unless $ok;
}

open my $ofh, '>>', $archfile or die "Cannot open $archfile for writing: $!";
print $ofh $ytext;
close $ofh;
