Author: brian d foy <briandfoy@pobox.com>
Title: CPAN::Audit interesting title to come
Topic: Find known vulnerabilities in your Perl installation

=encoding utf8

=head1 CPAN::Audit interesting title to come

L<CPAN::Audit> is a tool to scan your Perl installation and match what it finds with known vulnerabilities. Run the <cpan-audit> script with what you want to scan (just project dependencies or everything) to get a report:

		$ cpan-audit installed
	Collecting all installed modules. This can take a while...
	Data-UUID (have 1.226) has 1 advisory
	  * CPANSA-Data-UUID-2013-4184
		Perl module Data::UUID from CPAN version 1.219 vulnerable to symlink attacks

		Affected range: >1.219

		CVEs: CVE-2013-4184

		References:
		https://bugzilla.suse.com/show_bug.cgi?id=CVE-2013-4184
		http://www.openwall.com/lists/oss-security/2013/07/31/4
		http://www.securityfocus.com/bid/61534
		https://exchange.xforce.ibmcloud.com/vulnerabilities/86103
		https://security-tracker.debian.org/tracker/CVE-2013-4184
		https://access.redhat.com/security/cve/cve-2013-4184
		https://bugs.gentoo.org/show_bug.cgi?id=CVE-2013-4184

	File-Temp (have 0.2311) has 1 advisory
	  * CPANSA-File-Temp-2011-4116
		_is_safe in the File::Temp module for Perl does not properly handle symlinks.

		Affected range: >0

		CVEs: CVE-2011-4116

		References:
		http://www.openwall.com/lists/oss-security/2011/11/04/2
		https://rt.cpan.org/Public/Bug/Display.html?id=69106
		https://github.com/Perl-Toolchain-Gang/File-Temp/issues/14
		http://www.openwall.com/lists/oss-security/2011/11/04/4
		https://seclists.org/oss-sec/2011/q4/238

	Total advisories found: 2
