Title: Geocoding the world at volume with open data
Topic: Geo::Coder::OpenCage
Author: Ed Freyfogle <edf@opencagedata.com>    

=head1 Open Geo Data saves the day

Santa stood up from the desk and shook his head in disgust. 

“No, this just won’t do at all,” he mumbled. The gentle melody of carols in the background couldn’t hide the sense of disgust in his voice. 

“What is it?” asked the Head Elf, while studiously double checking the present list on his clipboard.

“As if the massive bill wasn’t enough, you should see the insane terms and conditions those clowns over at megacorp want us to agree to to use their geocoding services. This, my little friend, is the final straw. For years we’ve talked about it, and this year we are going to do it. We need to switch to using open geo data. I’ve seen more and more good things about the OpenStreetMap project. Thousands of contributors around the world, millions of edits per day. We shouldn’t just be using open-source software, we should also be using Open Data!!!”

“Umm, but Santa, Christmas is only a few weeks away, and the engineers are already completely overloaded. OpenStreetMap is great, I agree, but we really don’t have time to get anyone up to speed on it.” answered the Elf. 


