=head1 NAME

Promises - who has promised an article

=head1 DESCRIPTION

This lists who has promised an article for 2015 advent calendar.


=head2 Calendar

=over

=item 1st: DONE: Mark's GeoIP2 article

=item 2nd: DONE: Shoichi Kaji's App::cpm article

=item 3rd: DONE: Graham's FFI::Plat article

=item 4th: DONE: Evil's Devel::Hide article

=item 5th: DONE: Davorg's Lingua::EN::Inflexion article

=item 6th: DONE: Dave P's Convert::CookingTimes article

=item 7th: DONE: Alex's Text::Hogan article

=item 8th: DONE: James' Reply article

=item 9th: DONE: Yanic's Web::Query article

=item 10th DONE: Mark's CPANFILE article

=item 11th: DONE: Neil Bower's article

=item 12th: DONE Reserved for fREW's article

=item 13th: DONE Reserved for Yanick's JSON::Path Article

=item 14th: DONE: Mark's Acme::MetaSyntactic article

=item 15th: DONE: Yanick's File::Serialize article

=item 16th: DONE: Dave Rolsky's article

=item 17th: DONE: rjbs's article

=item 18th: Reserved for Ivan's article

The first draft of this is in, I just need to rework it at his request

WORK FOR MARK HERE

=item 19th: DONE Olaf's article

=item 20th: Reserved for 松木雅幸's article

First draft in.  Needs copyediting.

WORK FOR MARK HERE

=item 21st: Reserved for Maxim Vuets

Spoke to m, he's going to get it to me a few days before the 21st

=item 22nd: DONE: Marcus' article

=item 23rd: DONE Mark's article on Mojo::UserAgent

=item 24th: Reserved for Paul Evan's Article

Paul is working on an article on Hardware with Perl.  Mark may need to write
a little of this.

POTENTIAL WORK FOR MARK HERE

=item 25th: Thank you page / Mark's feature article

Not sure which we'll use here yet.

WORK FOR MARK HERE

=back

=head2 Other

=over

=item David Golden

On 2015-05-26: "Can't commit this early. Feel free to ask in November if you
have holes to fill"

=back

=head2 Ideas for Future Articles

Possible ideas if someone fails to deliver:

=over

=item App::cpanminus

Easy installation from the commmand line from the cpan.  Installing a previous
version from the CPAN.  Installing from a checkout.  Installing direct from
github.

=item List::Gather

=item http://www.slideshare.net/junichiishida/great-tools-heavily-used-in-japan-you-dont-know

There's a lot of modules here that are worth writing about

=item https://github.com/hachiojipm/awesome-perl

List of awesome modules

=back


