=head1 NAME

Promises - who has promised an article

=head1 DESCRIPTION

This lists who has promised an article for 2015 advent calendar.

In a summary:
  
=over

=item Three articles have been written

=item Three articles have first draft written

=item Twelve articles are actively being worked upon (three by Mark)

=back

In total B<EIGHTEEN> articles have reasonable chance of delivery if Mark does nothing (but write articles he's working on)

Potential Other Articles include:

=over

=item Four articles were planned but authors are currently AWOL

=item Three possible other articles could be written (Yanic x2, David Golden) if we ask

=back

There are B<SEVEN> more potential sources of articles therefore, taking us to B<TWENTY SIX> articles if Yanic overworks himself and no-one drops out (not likely)

=head2 Delivered

=over

=item Reply

Thanks James Laver

=item Alex Balhatchet

Text::Hogan

=item Mark Fowler: GeoIP2

An article on the elves struggle to build a real-time on-the-ground problem reporting website, using GeoIP2 to locate the map on the web interface

=back

=head2 First Draft In:

=over

=item Dave Cross

Dave was going to write about Lingua::EN::Inflexion

Status: Dave delivered the first draft 2015-11-14.  Feedback worked on, and he'll be delivering 2015-11-16ish

=item fREW Schmidt

Is going to write about Config::Station

Status First draft delivered 2015-11-14.  Feedback worked on.

=item Neil Bowers

Is going to write about Smart::Comments

Status: first draft in

=back

=head2 Promised, but not Planned

=over

=item Paul Evans

Says he'll write an article if we give him a good idea of what to write about.

=item Daisuke Maki

Says he's going to write about Plack or XS, but hasn't been more specific

=item Diego Kuperman

=back

=head2 Promised, and Planned and actively working on it

=over

=item Dave Rolsky

Dave is going to be writing about the Elves using Stepford to make the naughty and nice list, and has promised to deliver by December 1st.

=item Mark Fowler: feature

An article on using the feature pragma to load the new and exciting features in Perl

Status: Mostly written

=item Mark Fowler: cpanfile

An aritcle on using cpanfile (and other parts)

Status: Mostly done, needs tidying and formatting

=item Mark Fowler: Acme::MetaSyntactic

An article on the I<poor man's debugger> using C<print STDERR "crunch_eth clank_est\n";>.  Discusses lots about how to shell out to Perl from OS X

Status: The bit on Acme::MetaSyntactic is done, need to flesh out the OS X bit

=item Ricardo Signes

Is hoping to write about Lexical::Var

Status: Chaser irc message sent 2015-11-10.  Chaser acknowledged 2015-11-10. 

=item David Cantrell

Was going to pick Devel::Hide, talk about testing code both with and without optional dependencies, and maybe about some of the more evil things you can do with sub-refs in @INC.

Status:  Dave says he'll need another week (i.e. by 2015-11-18)

=item Yanick Champoux 

Yanick was going to write about one of JSON::Path / Web::Query / File::Serialize

Chased via email 2015-11-10.  Replied 2015-11-10 saying he was waiting to know which of these he wanted to write about, and if I wanted him to write about more than one (which I said yes please)

=item Maxim Vuets 

Maxim would like to write
about basic techniques to do fuzzy string matching in Perl. I'm going
to cover Text::Fuzzy, Data::CosineSimilarity, Text::Ngram, and
Text::Soundex at least.

Chased via email 2015-11-10.  Replied 2015-11-10 saying "this week"

=item Olaf Alders

Is going to write about Sort::ByExample

Chased by a Slack on 2015-11-10.  He gave me a thumbs up, which I assume means he's working on it.

=item Ivan Kruglov

Is going to write about Sereal

Last contact 2015-11-08 saying he'd send over his first draft that evening.

=item Shoichi Kaji

Sholichi is going to write about C<cpm>, and should have something by 2015-11-22

=back

=head2 Promised, Planned, but AWOL

=over

=item Marcus Ramberg

Is going to write about Marvin

Chased via email 2015-11-10.  Re-chased 2015-11-14.

=item Graham Ollis

Graham was going to write about FFI::Platypus and Rust integration.

Chased via email 2015-11-10

=item David Precious

Is going to write about Data::Censor / Convert::CookingTimes /  Dancer::Plugin::Auth::Extensible

Chased via email 2015-11-10.

=item 松木雅幸

Is going to write about "Perl and Redis" and Redis::Fast / Redis::LeaderBoard

Chased via email 2015-11-10

=back

=head2 Other

=over

=item David Golden

On 2015-05-26: "Can't commit this early. Feel free to ask in November if you
have holes to fill"

=back

=head2 Ideas for Future Articles

Possible ideas if someone fails to deliver:

=over

=item App::cpanminus

Easy installation from the commmand line from the cpan.  Installing a previous
version from the CPAN.  Installing from a checkout.  Installing direct from
github.

=item List::Gather

=item http://www.slideshare.net/junichiishida/great-tools-heavily-used-in-japan-you-dont-know

There's a lot of modules here that are worth writing about

=item https://github.com/hachiojipm/awesome-perl

List of awesome modules

=back


