=head1 NAME

Promises - who has promised an article

=head1 DESCRIPTION

This lists who has promised an article for 2015 advent calendar.

In a summary:

=over

=item There are zero articles delivered and in the queue

=item There are zero articles delivered pending being moved in the queue

=item Mark has written and committed zero articles so far

=item There are fourteen promises to write an article

=item There are zero articles planned

=back

=head2 Delivered

Nothing

=head2 Promised, but not Planned

=over

=item Alex Balhatchet

=item Dave Cantrell

=item Dave Cross

=item David Precious

=item Dave Rolsky

Dave says he'll be busy until Nov 1st but he's in

=item fREW Schmidt

=item Graham Ollis

=item James Laver

=item Marcus Ramburg

=item Neil Bowers

=item Olaf Alders

=item Paul Evans

Says he'll write an article if we give him a good idea of what to write about.

=item Ricardo Signes

=item Yanick Champoux

=back

=head2 Promised, and Planned

Nothing yet!

=over

=back

=head2 Other

=over

=item David Golden

On 2015-05-26: "Can't commit this early. Feel free to ask in November if you
have holes to fill"

=back

=head2 Ideas for Future Articles

Possible ideas if someone fails to deliver:

=over

=item Reply (and Ply)

=item App::cpanminus

Easy installation from the commmand line from the cpan.  Installing a previous
version from the CPAN.  Installing from a checkout.  Installing direct from
github.

=back


