=head1 NAME

2016 Perl Advent Calendar

=head1 STAGES

=head1 PROMISES

=head2 Delivered Initial Draft, Not Yet Copy Checked

=head3 Ed Freyfogle

Geo::Coder::OpenCage

=head3 perlancar

Bencher

=head3 Mark Allen

List::Util

=head3 Nicolas R.

PPI

=head3 Jerome Eteve

was going to be Mojolicious::Plugin::Sessions3S, but it seems we have a
module on Schedule::LongSteps instead.

=head3 Tina Müller

API::CLI

Tina put the article in a branch;  Asked her to move it into the main repo
2016-11-02

=head2 Delayed, But not AWOL

=head3 Jerrad Pierce

Text::Fuzzy

  I've not forgotten my articles, but it's taken more effort to
  create usable sample datasets than I anticipated. I hope to
  have drafts in within few days.

      -- 2016-11-02

=head3 Jerrad Pierce

Algorithm::Kmeans

 I've not forgotten my articles, but it's taken more effort to
 create usable sample datasets than I anticipated. I hope to
 have drafts in within few days.

    -- 2016-11-02

=head3 Raja Renga Bashyam

PDF::Reuse

Said on slack she'd have something by the seventh -- 2010-11-02

=head3 Doug Bell

Log::Any

Doug didn't get the invite email because I (Mark) was working off an old list
when I sent them out to everyone.  Ooops.  He says he can get started at the
weekend (2016-11-02)

=head2 Totally AWOL

=head3 David Cantrell

Params::Validate::Dependencies

=head3 Eugen Konkov

Devel::DebugHooks

=head3 Paul Evans

Syntax::Keyword::Try

=head3 Zak Elep

Mojolicious

=head3 Marian Marinov

Linux::Setns

=head3 Sawyer X

Ref::Util

=head3 Ervin Ruci

Geo::Parser::Text

=head3 Tux

Text::CSV_XS

=head3 Theo van Hoesel

HTTP::Caching

=head3 Chris Prather

Magpie / Web::Machine

=head3 JJ Merelo

Git::Hooks

=head3 Ruth Bavousett

Perl::Critic

=head3 Max Maischein

Dancer::SearchApp
