#!/usr/bin/env perl

package Perl::Advent::new_article;

use v5.10;
use strict;
use warnings;

use File::Spec::Functions;
use File::Path qw(make_path);
use Getopt::Long qw(GetOptions);

=head1 NAME

script/new_article - start a new Advent calendar article

=head1 SYNOPSIS

    % perl script/new_article
    Article title > Another article
    Article topic > Module::Covered::In::Article
    Author (Your Name) > brian d foy <bdfoy@cpan.org>
    Saved the starter article in 2022/incoming/another-article.pod

    Then edit your article and check it:

    % perl t/article_pod.t 2022/incoming/another-article.pod

    If you're preparing an article outside the active calendar year:

    % perl script/new_article --year 2025

    Non-interactive mode:

    % perl script/new_article --year 2025 --title "OpenAPI::Linter" \
      --topic OpenAPI::Linter --author "Your Name <mail\@example.com>"

=cut

sub run {
    my ( $year, $title, $topic, $author ) = parse_options();
    $year = $year // (localtime)[5] + 1900;
    die "Year must be a 4-digit value\n" unless $year =~ /\A\d{4}\z/;

    ( $title, $topic, $author ) = get_metadata( $title, $topic, $author );
    my $starter_text = cook_template( $title, $topic, $author );

    my $dir = catfile( $year, 'incoming' );
    make_path $dir;

    my $slug = slugify_title($title);
    my $path = catfile( $dir, "$slug.pod" );
    save_file( $starter_text, $path );
    say "Saved the starter article in $path";

    return $path;
}

sub parse_options {
    my ( $year, $title, $topic, $author );

    GetOptions(
        'year=i'   => \$year,
        'title=s'  => \$title,
        'topic=s'  => \$topic,
        'author=s' => \$author,
    ) or die "Usage: $0 [--year YYYY] [--title TITLE] [--topic TOPIC] [--author AUTHOR]\n";

    return ( $year, $title, $topic, $author );
}

sub slugify_title {
    my ($title) = @_;
    ( my $slug = lc($title) ) =~ s/\W+/-/g;
    $slug =~ s/\A-+|-+\z//g;
    return $slug;
}

sub cook_template {
    my( $title, $topic, $author ) = @_;
    my $template = do { local $/; <main::DATA> };

    $template =~ s/%%TITLE%%/$title/g;
    $template =~ s/%%TOPIC%%/$topic/g;
    $template =~ s/%%AUTHOR%%/$author/g;

    $template;
    }

sub get_metadata {
    my ( $title, $topic, $author ) = @_;

    $title  //= prompt( 'Article title' ) // 'Some title';
    $topic  //= prompt( 'Article topic (Module::Covered::In::Article)' ) // 'Some topic';
    $author //= prompt( 'Author (Your Name <your_email@example.com>)' ) // '';
    return ( $title, $topic, $author );
    }

sub prompt {
    my($message) = @_;
    print "$message > " if -t STDIN;
    chomp( my $answer = scalar <STDIN> );
    return $answer;
    }

sub save_file {
    my( $text, $filename ) = @_;

    open my $fh, '>:encoding(UTF-8)', $filename
        or die "Could not open <$filename>: $!";
    print {$fh} $text;
    close $fh;
    }

run() unless caller;

1;

__END__
Author: %%AUTHOR%%
Title: %%TITLE%%
Topic: %%TOPIC%%

=encoding utf8

=head2 Making links

Your article here goes here. The title will automatically be added by the site
builder. Make links with L<anchor text|http://example.com>. For module links,
merely specify the module, like L<Pod::Simple>.

=head2 Inline code

Make literal code text like this: C<$x>. If the code has angle brackets,
double up the angle brackets with extra space before and after, like this
C<< $obj->method >>..

=head2 Block code

There are regular Pod code verbatim text, which are indented lines:

    my $x = 1_00_000 ** $::xyzzy;

A C<perl> section can do syntax highlighting

=begin perl

    # inside "perl" blocks, make syntax-highlighted code
    # with Pod::Elemental::Transformer::SynHi
    my $x = 1_00_000 ** $::xyzzy;

=end perl

A C<code> section can syntax-highlight non-Perl too:

=begin code

  # inside "code" blocks, make syntax-highlighted code
  # with Pod::Elemental::Transformer::Codebox

=end code

You can try vim syntax highlighting hints, such as declaring that a
snippet is JSON. The hint is the first line and indented at the same
level.

	#!vim json
	{
	"Name": "Donner",
	"aliases": [ "Dunder", "Donder" ],
	"start-date": "1823-12-24"
	}

=head2 Raw HTML

Include some raw HTML. If you are including static content, you can add it to a
C<share/static> folder within your YYYY folder. e.g.
C<2024/share/static/some-graphic.png>. A blank line breaks the HTML spell:

=for :html
<img src="some-graphic.png">
<p>Some para</p>

This is back to Pod. For big blocks of HTML, including blank lines,
use C<=begin html>.

=begin html

<p>Some para</p>

<p>Another para</p>

=end html

=head2 Lists

=for :list
* short list syntax from Pod::Elemental::Transformer::List
* duck
* duck
* goose

=cut
