Author: thibault.duponchelle@gmail.com
Title: Testing images
Topic: perl

=encoding utf8

=head1 Pictures and POD

=head2 Using for html

=for html
  <center><img src="600x400.png" alt="600x400"></center>

=head2 Using begin html

=begin html

<center><img src="600x400.png" alt="600x400"></center>

=end html

=head2 Not centered

=begin html

<img src="100x100.png" alt="100x100">

=end html

=head1 Pictures sizes

=head2 100x100

=for html
  <center><img src="100x100.png" alt="100x100"></center>

=head2 250x100

=for html
  <center><img src="250x100.png" alt="250x100"></center>

=head2 250x250

=for html
  <center><img src="250x250.png" alt="250x250"></center>

=head2 600x400

=for html
  <center><img src="600x400.png" alt="600x400"></center>

=head2 1200x600

=for html
  <center><img src="1200x600.png" alt="120x250"></center>

=head2 2000x1000

=for html
  <center><img src="2000x1000.png" alt="2000x1000"></center>

=head2 3000x2000

=for html
  <center><img src="3000x2000.png" alt="3000x2000"></center>

=head2 4000x4000

=for html
  <center><img src="4000x4000.png" alt="4000x4000"></center>

=cut
