Author: Thibault DUPONCHELLE <thibault.duponchelle@gmail.com>
Title: Testing formatting
Topic: perl

=encoding utf8

=head1 Head 1

This is a paragraph under Head 1

=head2 Head 2

Some test under Head 2

=head3 Head 3

Some more text under Head 3

=head4 Head 4

And finally under Head 4

=head2 Formatting

B<Bold> or I<Italic> or C<code>

=head2 Making links

A L<simple link to perl.com|http://perl.com> or a link to a module L<Pod::Simple>.

=head2 Lists

=for :list
* Foo
* Bar
* Baz

=cut
