Title: Test/Compare your Excel
Topic: Test::Excel
Author: Mohammad S Anwar <mohammad.anwar@yahoo.com>

Santa's elves have to deal with a wide range of suppliers throughout the year in order to get
all the parts for the toys they assemble at the North Pole.  Each one of these seems to have
their own particular workflow.

Spruce Glowchaser was dealing with a supplier that needed an Excel spreadsheet filled out and
emailed to them.  Over the last few weeks he'd painstakenly written the automation code to
generate the spreadsheet using L<Spreadsheet::WriteExcel>. He I<thought> he'd managed to
faithfully reproduce the example sheet from the supplier - that was until the QA department
had kicked back his output with numerous bugs.

"What you need to do", the Wise Old Elf had chagrined him, "is write some tests"

=head1 Description

It was first published to CPAN on 13th Aug 2010. My first contribution ever and very close to my heart.
It is important to understand the term "visually". It compares the data structure and ignores components
such as embedded fonts, images, forms and annotations.

The package Test::Excel exports the following methods

=over 4

=item cmp_excel_ok($got, $exp, \%$rule, $message)

The params C<$got> and C<$exp> can be path to the two Excel files being compared or it could be an object
of type L<Spreadsheet::ParseExcel>. The param C<\%rule> is optional. Finally the param C<$message> is the
test message, which is optional as well. It is ideal for use in unit test as below.

    use strict; use warnings;
    use Test::More;
    use Test::Excel;

    cmp_excel_ok('foo.xls', 'bar.xls');

    done_testing();

The C<cmp_excel()> is same as C<cmp_excel_ok()>.

=item cmp_execel_not_ok($got, $exp, \%$rule, $message)

Just the reverse of C<cmp_excel_ok()>. It is ideal for use in unit test as below.

    use strict; use warnings;
    use Test::More;
    use Test::Excel;

    cmp_excel_not_ok('foo.xls', 'bar.xls');

    done_testing();

=item compare_excel($got, $exp, \%$rule)

This is the core method that does all the job. It can be used as standalone method outside of test
environment.

     use strict; use warnings;
      use Test::Excel;

       print "EXCELs are identical.\n" if compare_excel("foo.xls", "bar.xls");

=back

=head1 RULES SPECIFICATION

If you noticed above, all the methods accept an optional parameter C<\%rule>. So what is this all about?
You can fine tune the comparison rule in the specification.

=over 4

=item spec

Path to specification file.

=item sheet

It contains "|" separated sheet names.

=item tolerance

Tolerance amount acceptable. Applicable to all except on 'sheet' or 'spec'

=item sheet_tolerance

Tolerance amount acceptable. Applicable only to 'sheet' or 'range' in the spec file.

=item swap_check

Boolean 0 or 1, whether row swapping check is on or off.

=item error_limit

Limit the number of errors acceptable. Default is 0.

=head1 SPECIFICATION FILE

The spcification file contains space separated key value pair per line. It can have the following keys:

=over 4

=item sheet

Sheet name in the Excel file.

=item range

Cell range.

=item ignorerange

Cell range to ignore when comparing.

=back

=head1 EXAMPLES

You can find loads of example in the L<distribution|https://metacpan.org/pod/Test::Excel>.

=head1 CONTRIBUTIONS

If you any suggestions to improve or found bugs in the code then please raise it on L<GitHub|https://github.com/manwar/Test-Excel>.

=cut
