Title:  Built in Our Workshop, Delivered in Your Package
Package: Sub::Exporter

=head1 Unicode Hell

🌴 🐪🐫🐪🐫🐪 🌞 𝕲𝖔  𝕿𝖍𝖔𝖚  𝖆𝖓𝖉  𝕯𝖔  𝕷𝖎𝖐𝖊𝖜𝖎𝖘𝖊 🌞 🐪🐫🐪 🐁

𝓔𝓭𝓲𝓽 :  𝙎𝙞𝙢𝙥𝙡𝙚𝙨𝙩 ℞:  𝟕 𝘿𝙞𝙨𝙘𝙧𝙚𝙩𝙚  𝙍𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙𝙖𝙩𝙞𝙤𝙣𝙨

Verbatim:

  🌴 🐪🐫🐪🐫🐪 🌞 𝕲𝖔  𝕿𝖍𝖔𝖚  𝖆𝖓𝖉  𝕯𝖔  𝕷𝖎𝖐𝖊𝖜𝖎𝖘𝖊 🌞 🐪🐫🐪 🐁

  𝓔𝓭𝓲𝓽 :  𝙎𝙞𝙢𝙥𝙡𝙚𝙨𝙩 ℞:  𝟕 𝘿𝙞𝙨𝙘𝙧𝙚𝙩𝙚  𝙍𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙𝙖𝙩𝙞𝙤𝙣𝙨

Bare code:

  #!code
  🌴 🐪🐫🐪🐫🐪 🌞 𝕲𝖔  𝕿𝖍𝖔𝖚  𝖆𝖓𝖉  𝕯𝖔  𝕷𝖎𝖐𝖊𝖜𝖎𝖘𝖊 🌞 🐪🐫🐪 🐁

  𝓔𝓭𝓲𝓽 :  𝙎𝙞𝙢𝙥𝙡𝙚𝙨𝙩 ℞:  𝟕 𝘿𝙞𝙨𝙘𝙧𝙚𝙩𝙚  𝙍𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙𝙖𝙩𝙞𝙤𝙣𝙨

Perl highlighted:

  #!perl

  my $str = q{
    🌴 🐪🐫🐪🐫🐪 🌞 𝕲𝖔  𝕿𝖍𝖔𝖚  𝖆𝖓𝖉  𝕯𝖔  𝕷𝖎𝖐𝖊𝖜𝖎𝖘𝖊 🌞 🐪🐫🐪 🐁
    𝓔𝓭𝓲𝓽 :  𝙎𝙞𝙢𝙥𝙡𝙚𝙨𝙩 ℞:  𝟕 𝘿𝙞𝙨𝙘𝙧𝙚𝙩𝙚  𝙍𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙𝙖𝙩𝙞𝙤𝙣𝙨
  };

Vim highlighted:

  #!vim perl
  🌴 🐪🐫🐪🐫🐪 🌞 𝕲𝖔  𝕿𝖍𝖔𝖚  𝖆𝖓𝖉  𝕯𝖔  𝕷𝖎𝖐𝖊𝖜𝖎𝖘𝖊 🌞 🐪🐫🐪 🐁

  𝓔𝓭𝓲𝓽 :  𝙎𝙞𝙢𝙥𝙡𝙚𝙨𝙩 ℞:  𝟕 𝘿𝙞𝙨𝙘𝙧𝙚𝙩𝙚  𝙍𝙚𝙘𝙤𝙢𝙢𝙚𝙣𝙙𝙖𝙩𝙞𝙤𝙣𝙨

=head1 See Also

=for :list
* L<http://stackoverflow.com/questions/6162484/why-does-modern-perl-avoid-utf-8-by-default>

